services:
  db:
    image: mariadb:10.1
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3308:3306'

  foodsoft_web:
    extends:
      file: foodsoft-common.yml
      service: foodsoft
    command: ./proc-start web
    ports:
      - '3000:3000'

  foodsoft_worker:
    extends:
      file: foodsoft-common.yml
      service: foodsoft
    command: ./proc-start worker

  redis:
    image: redis:3.2-alpine

volumes:
  bundle:
  db:
