version: '3'
services:
  db:
    image: mariadb:10.1
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3306:3306'

  foodsoft:
    tty: true
    stdin_open: true
    command: ./proc-start web
    depends_on:
      - db
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile-dev
    restart: always
    volumes:
      - bundle:/home/app/bundle
      - .:/home/app/src
    environment:
      - DATABASE_URL=mysql2://root:@db/development?encoding=utf8
#      - TEST_DATABASE_URL=mysql2://root:@db/test?encoding=utf8
#      - REDIS_URL=redis://redis:6379
#      - QUEUE=foodsoft_notifier

#  mailcatcher:
#    image: aboutsource/mailcatcher
#    ports:
#      - "1080:1080"

#  redis:
#    image: redis:3.2-alpine

volumes:
  bundle:
  db:
